-- Baseline schema for REX Platform.
-- Generated from the JPA entities and frozen here. From this point Flyway owns the schema
-- and Hibernate runs with ddl-auto=validate, so entity drift fails startup instead of
-- silently rewriting tables.

CREATE TABLE public.experiments (
    confidence_level double precision,
    current_sample_size integer,
    expected_improvement double precision,
    minimum_sample_size integer,
    traffic_percentage integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    end_date timestamp(6) without time zone,
    id bigint NOT NULL,
    start_date timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    created_by character varying(100),
    name character varying(100) NOT NULL,
    description character varying(1000),
    hypothesis character varying(2000),
    control_variant_name character varying(255) NOT NULL,
    environment character varying(255),
    status character varying(255) NOT NULL,
    success_metric character varying(255),
    test_variant_name character varying(255) NOT NULL,
    CONSTRAINT experiments_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'READY'::character varying, 'RUNNING'::character varying, 'PAUSED'::character varying, 'COMPLETED'::character varying, 'ARCHIVED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT experiments_traffic_percentage_check CHECK (((traffic_percentage <= 100) AND (traffic_percentage >= 1)))
);

ALTER TABLE public.experiments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.experiments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.feature_flags (
    enabled boolean NOT NULL,
    rollout_percentage integer,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    created_by character varying(100),
    name character varying(100) NOT NULL,
    description character varying(500),
    environment character varying(255),
    status character varying(255) NOT NULL,
    CONSTRAINT feature_flags_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'ARCHIVED'::character varying, 'DEPRECATED'::character varying])::text[])))
);

ALTER TABLE public.feature_flags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feature_flags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.metrics (
    conversion_value double precision,
    count_value integer,
    event_value double precision,
    revenue double precision,
    duration_ms bigint,
    experiment_id bigint,
    feature_flag_id bigint,
    id bigint NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    ip_address character varying(45),
    device_type character varying(50),
    platform character varying(50),
    event_name character varying(100),
    variant_name character varying(100),
    user_agent character varying(500),
    error_message character varying(1000),
    page_url character varying(1000),
    referrer_url character varying(1000),
    properties character varying(2000),
    environment character varying(255),
    event_type character varying(255) NOT NULL,
    session_id character varying(255),
    user_id character varying(255) NOT NULL,
    CONSTRAINT metrics_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['FLAG_EXPOSURE'::character varying, 'FLAG_ENABLED'::character varying, 'FLAG_DISABLED'::character varying, 'FLAG_TOGGLED'::character varying, 'EXPERIMENT_EXPOSURE'::character varying, 'EXPERIMENT_ASSIGNMENT'::character varying, 'PAGE_VIEW'::character varying, 'CLICK'::character varying, 'IMPRESSION'::character varying, 'CONVERSION'::character varying, 'PURCHASE'::character varying, 'SIGNUP'::character varying, 'LOGIN'::character varying, 'LOAD_TIME'::character varying, 'API_RESPONSE_TIME'::character varying, 'ERROR'::character varying, 'EXCEPTION'::character varying, 'CUSTOM'::character varying])::text[])))
);

ALTER TABLE public.metrics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metrics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_cohorts (
    assignment_hash integer,
    exposure_count integer,
    is_active boolean,
    assigned_at timestamp(6) without time zone NOT NULL,
    experiment_id bigint NOT NULL,
    first_exposure_at timestamp(6) without time zone,
    id bigint NOT NULL,
    last_exposure_at timestamp(6) without time zone,
    user_attributes character varying(1000),
    assignment_method character varying(255) NOT NULL,
    cohort_type character varying(255) NOT NULL,
    environment character varying(255),
    session_id character varying(255),
    user_id character varying(255) NOT NULL,
    variant_name character varying(255) NOT NULL,
    CONSTRAINT user_cohorts_assignment_method_check CHECK (((assignment_method)::text = ANY ((ARRAY['HASH_BASED'::character varying, 'RANDOM'::character varying, 'MANUAL'::character varying, 'ATTRIBUTE_BASED'::character varying, 'PERCENTAGE_BASED'::character varying])::text[]))),
    CONSTRAINT user_cohorts_cohort_type_check CHECK (((cohort_type)::text = ANY ((ARRAY['CONTROL'::character varying, 'TREATMENT'::character varying, 'EXCLUDED'::character varying])::text[])))
);

ALTER TABLE public.user_cohorts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_cohorts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.experiments
    ADD CONSTRAINT experiments_name_key UNIQUE (name);

ALTER TABLE ONLY public.experiments
    ADD CONSTRAINT experiments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.feature_flags
    ADD CONSTRAINT feature_flags_name_key UNIQUE (name);

ALTER TABLE ONLY public.feature_flags
    ADD CONSTRAINT feature_flags_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.metrics
    ADD CONSTRAINT metrics_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_cohorts
    ADD CONSTRAINT user_cohorts_pkey PRIMARY KEY (id);

CREATE INDEX idx_metrics_event_type ON public.metrics USING btree (event_type);

CREATE INDEX idx_metrics_experiment_id ON public.metrics USING btree (experiment_id);

CREATE INDEX idx_metrics_feature_flag_id ON public.metrics USING btree (feature_flag_id);

CREATE INDEX idx_metrics_timestamp ON public.metrics USING btree ("timestamp");

CREATE INDEX idx_metrics_user_experiment ON public.metrics USING btree (user_id, experiment_id);

CREATE INDEX idx_metrics_user_flag ON public.metrics USING btree (user_id, feature_flag_id);

CREATE INDEX idx_metrics_user_id ON public.metrics USING btree (user_id);

CREATE INDEX idx_user_cohorts_experiment_id ON public.user_cohorts USING btree (experiment_id);

CREATE INDEX idx_user_cohorts_user_experiment ON public.user_cohorts USING btree (user_id, experiment_id);

CREATE INDEX idx_user_cohorts_user_id ON public.user_cohorts USING btree (user_id);

ALTER TABLE ONLY public.user_cohorts
    ADD CONSTRAINT fkck6otkhtsukpkxyfoyafer69s FOREIGN KEY (experiment_id) REFERENCES public.experiments(id);

ALTER TABLE ONLY public.metrics
    ADD CONSTRAINT fkgkctgtrqyt4q5m7im7y0yfikf FOREIGN KEY (feature_flag_id) REFERENCES public.feature_flags(id);

ALTER TABLE ONLY public.metrics
    ADD CONSTRAINT fktqrifdm4y45tne1dbcno329yf FOREIGN KEY (experiment_id) REFERENCES public.experiments(id);

