-- Persistence for attribute based targeting.
--
-- The evaluation engine has understood rules since Phase 2, but nothing stored them, so the
-- feature existed in the code and could never be configured. This table is what makes it reachable.

CREATE TABLE targeting_rules (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_flag_id bigint NOT NULL REFERENCES feature_flags (id) ON DELETE CASCADE,
    rule_order      integer NOT NULL,
    attribute       varchar(100) NOT NULL,
    operator        varchar(30) NOT NULL,
    -- Comma separated rather than a child table: a rule's values are read together, never
    -- queried individually, and a join per rule per evaluation would not earn its cost.
    values_csv      varchar(1000) NOT NULL,
    enable          boolean NOT NULL,
    CONSTRAINT targeting_rules_operator_check
        CHECK (operator IN ('EQUALS', 'NOT_EQUALS', 'IN', 'NOT_IN', 'CONTAINS',
                            'GREATER_THAN', 'LESS_THAN', 'VERSION_GREATER_OR_EQUAL')),
    CONSTRAINT targeting_rules_order_unique UNIQUE (feature_flag_id, rule_order)
);

-- Rules are loaded per flag on evaluation, ordered, so first match wins deterministically.
CREATE INDEX idx_targeting_rules_flag ON targeting_rules (feature_flag_id, rule_order);
