-- Staged rollout schedules.
--
-- A schedule advances a flag through increasing percentages on a clock rather than requiring an
-- operator to sit and watch. Stage state is persisted rather than held in memory so a restart
-- mid rollout resumes where it left off instead of starting again.

CREATE TABLE rollout_schedules (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_flag_id     bigint NOT NULL REFERENCES feature_flags (id),
    status              varchar(20) NOT NULL,
    current_stage_index integer NOT NULL DEFAULT 0,
    stage_entered_at    timestamp(6),
    last_safe_percentage integer NOT NULL DEFAULT 0,
    created_by          varchar(100),
    created_at          timestamp(6) NOT NULL,
    updated_at          timestamp(6),
    completed_at        timestamp(6),
    halted_reason       varchar(500),
    CONSTRAINT rollout_schedules_status_check
        CHECK (status IN ('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'ROLLED_BACK')),
    CONSTRAINT rollout_schedules_flag_unique UNIQUE (feature_flag_id)
);

CREATE TABLE rollout_stages (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rollout_schedule_id  bigint NOT NULL REFERENCES rollout_schedules (id) ON DELETE CASCADE,
    stage_order          integer NOT NULL,
    target_percentage    integer NOT NULL,
    dwell_minutes        integer NOT NULL,
    CONSTRAINT rollout_stages_percentage_check
        CHECK (target_percentage BETWEEN 0 AND 100),
    CONSTRAINT rollout_stages_dwell_check CHECK (dwell_minutes > 0),
    CONSTRAINT rollout_stages_order_unique UNIQUE (rollout_schedule_id, stage_order)
);

-- The sweep selects running schedules on every tick, so it should not scan the whole table.
CREATE INDEX idx_rollout_schedules_status ON rollout_schedules (status);
