-- Append only record of every configuration change.
--
-- Written in the same transaction as the change it describes, so a change cannot exist without its
-- audit row. Automated actions attribute to the scheduler rather than a user, which is what makes
-- an automatic rollback traceable after the fact.

CREATE TABLE audit_events (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor        varchar(100) NOT NULL,
    action       varchar(50) NOT NULL,
    target_type  varchar(50) NOT NULL,
    target_id    bigint,
    target_name  varchar(100),
    before_value varchar(500),
    after_value  varchar(500),
    reason       varchar(500),
    environment  varchar(50),
    occurred_at  timestamp(6) NOT NULL
);

-- The audit feed reads most recent first for one target, and the dashboard reads the whole feed.
CREATE INDEX idx_audit_events_target ON audit_events (target_type, target_id, occurred_at DESC);
CREATE INDEX idx_audit_events_occurred ON audit_events (occurred_at DESC);
